### ISSUE TITLE
Bug with Win platform

### ISSUE THREAD

**Issue by cptLiVSi** [opendatadiscovery/odd-collector-sdk#11]
In the path to the modules (windows platform) there are "\\" instead of "."

ERROR in odd-collector-aws: No module named 'odd_collector_aws.adapters.s3\\adapter'
Traceback (most recent call last):
  File "C:\projects\odd-collector-aws\odd_collector_aws\__main__.py", line 24, in <module>
    collector = Collector(str(config_path), root_package, PLUGIN_FACTORY)

**Comment by DementevNikita** [comment]
hey @cptLiVSi!
Thank you for letting us know!

@Vixtir could you look at this?
